Skymavis library for Jenkins CICD

You can find detailed information about all of these libraries here: [linlk](https://www.jenkins.io/blog/2019/05/09/templating-engine/)

== What is JTE?

Organizations benefit from letting application developers focus on what they do best: building applications. Supporting this means building a centralized DevOps team responsible for maintaining platform infrastructure and creating CI/CD pipelines utilized by development teams.

With the rise of microservice-based architectures, a centralized DevOps teams can support many different development teams simultaneously; all of whom may be leveraging different programming languages and automated testing tools.

Example Pipeline Template:
```
agent {
  on_pull_request to: main, {
    in_dir in: "graphql/*/.*.rs", {
      sh "Runing everywher in step"
      build()
      deploy_to_gke cluster_dev
    }
  }
}
```
or with agnet input yaml
```
agent_advance(yaml: """
spec:
  containers:
  - command:
    - "cat"
    image: "axieinfinity/axie-docker-dind-gcloud:latest"
    name: "docker-dind-gcloud"
    resources:
      limits: {}
      requests: {}
    securityContext:
      privileged: true
    tty: true
    volumeMounts:
    - mountPath: "/root/.gcloud"
      name: "volume-2"
      readOnly: false
    - mountPath: "/var/lib/docker"
      name: "volume-0"
      readOnly: false
    - mountPath: "/var/run/docker.sock"
      name: "volume-1"
      readOnly: false
    - mountPath: "/home/jenkins/agent"
      name: "workspace-volume"
      readOnly: false
  volumes:
  - emptyDir:
      medium: ""
    name: "volume-0"
  - configMap:
      name: "helm-secrets-confimap"
    name: "volume-2"
  - hostPath:
      path: "/var/run/docker.sock"
    name: "volume-1"
  - emptyDir:
      medium: ""
    name: "workspace-volume"
""") {...}
```
on_* steps example: on_commit, on_pull_request, on_merge, on_pull_request, on_merge

`Note: Read code more detailed. Happy coding =))`
